services:
  reproducible-ml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab2_reproducible_ml
    volumes:
      - .:/app
    working_dir: /app
    command: dvc repro
